# Basic of pyTorch

In [1]:
# Import some libaray
import numpy as np
import torch as tr

# initializing a numpy array
a = np.array(1)

# initializing a torch array
b = tr.tensor(1)

print(a)
print(b)

1
tensor(1)


In [2]:
type(a), type(b)

(numpy.ndarray, torch.Tensor)

## Mathematical operations

In [5]:
# initializing two arrays in numpy
a = np.array(2)
b = np.array(1)
print(a,b)

2 1


In [4]:
# addition
print(a+b)

# subtraction
print(b-a)

# multiplication
print(a*b)

# division
print(a/b)

3
-1
2
2.0


In [10]:
# initializing two tensors
a = tr.tensor(2)
b = tr.tensor(1)
print(a,b)

# addition
print(a+b)

# subtraction
print(b-a)

# multiplication
print(a*b)

# division
print(a/b)

tensor(2) tensor(1)
tensor(3)
tensor(-1)
tensor(2)
tensor(2.)


## Matrix Initialization
Let\'s se the matrix initilization of both parameters

In [13]:
a = np.zeros((3,3))
print(a)
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)


In [14]:
b = tr.zeros((3,3))
print(b)
print(b.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([3, 3])


In [18]:
# with a random number
# seeting the random seed for numpy
np.random.seed(35)
a = np.random.randn(3,3)
print(a)

[[-1.88973671 -0.41359218 -0.76602601]
 [-0.92412667 -1.42159783  0.80525599]
 [ 1.14886176  1.1694284  -0.80200928]]


In [21]:
# with a random number , torch
# seeting the random seed for torch
tr.manual_seed(42)
# matrix of random numbers
b = tr.randn(3,3)
print(b)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])


## Matrix Operations
let's have a matrix operation

In [25]:
# seeting the random seed for numpy and initializing two matrices
np.random.seed(42)
a = np.random.randn(3,3)
b = np.random.randn(3,3)

# matrix addition
print(np.add(a,b), '\n')

# matrix subtraction
print(np.subtract(a,b), '\n')

# matrix multiplication
print(np.dot(a,b), '\n')

# matrix multiplication
print(np.divide(a,b), '\n')

# Matrix transpose
print(np.transpose(a))


[[ 1.0392742  -0.60168199  0.18195878]
 [ 1.76499213 -2.14743362 -1.95905479]
 [ 1.01692529 -0.24539639 -0.15522705]] 

[[-0.04584589  0.32515339  1.11341829]
 [ 1.28106758  1.67912687  1.49078088]
 [ 2.14150034  1.78026585 -0.78372172]] 

[[-0.12814468 -0.62164688  0.21069439]
 [ 0.90133115 -0.02065676 -0.3790019 ]
 [ 1.30648762 -1.7246546  -2.20677932]] 

[[ 0.9155008   0.29835784 -1.39069607]
 [ 6.29449313  0.12238321  0.13573803]
 [-2.80855031 -0.75771243 -1.49396459]] 

[[ 0.49671415  1.52302986  1.57921282]
 [-0.1382643  -0.23415337  0.76743473]
 [ 0.64768854 -0.23413696 -0.46947439]]


In [28]:
# Let's try the pytorch for matries operation
tr.manual_seed(42)
c = tr.randn(3,3)
d = tr.randn(3,3)

# matrix operation: addition
print(tr.add(c,d), '\n')

# matrix operation: subtraction
print(tr.sub(c,d), '\n')

# matrix operation: multiplication
print(tr.mm(c,d), '\n')

# matrix operation: division
print(tr.div(c,d), '\n')


# matrix tranpose
tr.t(c)

tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]]) 

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]]) 

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]]) 

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]]) 



tensor([[ 0.3367,  0.2303,  2.2082],
        [ 0.1288, -1.1229, -0.6380],
        [ 0.2345, -0.1863,  0.4617]])

## Concatenating Tensors

In [30]:
# initializing two tensors
a = tr.tensor([[1,2],[3,4]])
b = tr.tensor([[5,6],[7,8]])
print(a, '\n')
print(b)

tensor([[1, 2],
        [3, 4]]) 

tensor([[5, 6],
        [7, 8]])


In [31]:
# to concatenating vertically
tr.cat((a,b))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [32]:
tr.cat((a,b),dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

## Common pyTorch Modules

In [2]:
# iniatializing a tensor
a = tr.ones((2,2), requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [3]:
# performing operations on the tensor

b = a + 5
c = b.mean()
print(b,c)

tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>) tensor(6., grad_fn=<MeanBackward0>)


In [10]:
# back propagating
c.backward()

print(a.grad)

tensor([[1.7500, 1.7500],
        [1.7500, 1.7500]])


### Building a Neural Network from Scratch in PyTorch

In [11]:
# Import tensor
X = tr.Tensor([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

# output
y = tr.Tensor([[1],[1],[0]])

print(X, '\n')
print(y)

tensor([[1., 0., 1., 0.],
        [1., 0., 1., 1.],
        [0., 1., 0., 1.]]) 

tensor([[1.],
        [1.],
        [0.]])


In [12]:
def sigmoid(x):
    return 1/(1+tr.exp(-x))

# derivative of sigmoid function
def derivative_sigmoid(x):
    return sigmoid(x)*(1-sigmoid(x))

In [13]:
# Variable initialization
epoch = 7000 # seeting training iterations

lr = 0.1 # set learning rate
input_layer_neurons = X.shape[1] # number of feature in dataset
hidden_layer_neurons = 3 # number of hidden layer neurons
output_neurons = 1 # number of neurons in output layer


# weight and bias initialization
wt = tr.randn(input_layer_neurons, hidden_layer_neurons).type(tr.FloatTensor)
bi = tr.randn(1, hidden_layer_neurons).type(tr.FloatTensor)
wtout = tr.randn(hidden_layer_neurons, output_neurons)
biout = tr.randn(1, output_neurons)

In [15]:
for i in range(epoch):
    # forward propagation
    hidden_layer_input1 = tr.mm(X, wt)
    hidden_layer_input = hidden_layer_input1 + bi
    hidden_layer_activations = sigmoid(hidden_layer_input)
    
    output_layer_input1 = tr.mm(hidden_layer_activations, wtout)
    output_layer_input = output_layer_input1 + biout
    output = sigmoid(output_layer_input)
    
    # back propagation
    E = y - output
    slop_output_layer = derivative_sigmoid(output)
    slop_hidden_layer = derivative_sigmoid(hidden_layer_activations)
    d_output = E * slop_output_layer
    
    Error_at_hidden_layer = tr.mm(d_output, wtout.t())
    d_hidden_layer = Error_at_hidden_layer * slop_hidden_layer
    wtout += tr.mm(hidden_layer_activations.t(), d_output)* lr
    biout += d_output.sum() * lr
    wt += tr.mm(X.t(), d_hidden_layer) * lr
    bi += d_output.sum() * lr

In [16]:
print('actual:\n', y,'\n')
print('predicted:\n', output)

actual:
 tensor([[1.],
        [1.],
        [0.]]) 

predicted:
 tensor([[0.9984],
        [0.9972],
        [0.0050]])


In [17]:
tr.cuda.is_available()

True

### Opeation on gpu

In [2]:
import torch as tr
import numpy as np

if tr.cuda.is_available():
    device = tr.device('cuda')
    x = tr.randn(5, device=device)
    y = tr.randn(5)
    
    y = y.to(device)
    z = x*y
    print(z)

tensor([ 0.8721,  0.9826, -0.9442, -0.9234,  0.2177], device='cuda:0')


In [4]:
 if tr.cuda.is_available():
        a = tr.ones(5, requires_grad=True)
        print(a)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


### Autograd

In [3]:
import torch as tr

if tr.cuda.is_available():
    x = tr.randn(3, requires_grad=True)
    print('x is: ', x)
    y = x + 2
    print('y is: ', y)
    
    z = x*x*2
    print('z is: ', z)
    
    z = z.mean()
    print('z1: ', z)
    
    z.backward()
    print(x.grad)

    
# how to prevent grad from the formulas
'''
- x.requires_grad(False)
- x.detach()
- with torch.no_grad()
'''

x is:  tensor([-1.0213, -1.9190,  0.5424], requires_grad=True)
y is:  tensor([0.9787, 0.0810, 2.5424], grad_fn=<AddBackward0>)
z is:  tensor([2.0861, 7.3653, 0.5883], grad_fn=<MulBackward0>)
z1:  tensor(3.3466, grad_fn=<MeanBackward0>)
tensor([-1.3617, -2.5587,  0.7232])


'\n- x.requires_grad(False)\n- x.detach()\n- with torch.no_grad()\n'

In [10]:
# an example of autograd
if tr.cuda.is_available():
    weight = tr.ones(4, requires_grad=True)
    
    for epach in range(3):
        model_output = (weight*3).sum()
        model_output.backward()
        
        print(model_output)
        print(weight.grad)
        
        #weight.grad.zero_()

tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])


### backpropagation

In [13]:
x = tr.tensor(1.0)
y = tr.tensor(2.0)

w = tr.tensor(1.0, requires_grad=True)

# forward pass and compute the loss
y_predict = w*x
loss = (y_predict - y)**2
print(loss)

# backward pass
loss.backward()
print(w.grad)

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


In [16]:
from torch.autograd import Variable
x_data = [1.0, 2.0, 3.0]
y_data = [2.0, 4.0, 6.0]

w = Variable(tr.Tensor([1.0]), requires_grad=True)

# our model forward pass
def forward(x):
    return x * w

# loss function
def loss(x, y):
    y_pred = forward(x)
    
    return (y_pred - y)**2

# before training
print("predict (before training)", 4, forward(4).data[0])

# training lossp
for epach in range(10):
    for x_val, y_val in zip(x_data,y_data):
        l = loss(x_val, y_val)
        l.backward()
        
        print("\tgrad: ", x_val, y_val, w.grad.data[0])
        w.data = w.data - 0.01 * w.grad.data
        
        # manually zero the gradiants after updaring weights
        w.grad.data.zero_()
        
    print("Progress:", epach, l.data[0])

# after training
print("Predict (after training)", 4, forward(4).data[0])

predict (before training) 4 tensor(4.)
	grad:  1.0 2.0 tensor(-2.)
	grad:  2.0 4.0 tensor(-7.8400)
	grad:  3.0 6.0 tensor(-16.2288)
Progress: 0 tensor(7.3159)
	grad:  1.0 2.0 tensor(-1.4786)
	grad:  2.0 4.0 tensor(-5.7962)
	grad:  3.0 6.0 tensor(-11.9981)
Progress: 1 tensor(3.9988)
	grad:  1.0 2.0 tensor(-1.0932)
	grad:  2.0 4.0 tensor(-4.2852)
	grad:  3.0 6.0 tensor(-8.8704)
Progress: 2 tensor(2.1857)
	grad:  1.0 2.0 tensor(-0.8082)
	grad:  2.0 4.0 tensor(-3.1681)
	grad:  3.0 6.0 tensor(-6.5580)
Progress: 3 tensor(1.1946)
	grad:  1.0 2.0 tensor(-0.5975)
	grad:  2.0 4.0 tensor(-2.3422)
	grad:  3.0 6.0 tensor(-4.8484)
Progress: 4 tensor(0.6530)
	grad:  1.0 2.0 tensor(-0.4417)
	grad:  2.0 4.0 tensor(-1.7316)
	grad:  3.0 6.0 tensor(-3.5845)
Progress: 5 tensor(0.3569)
	grad:  1.0 2.0 tensor(-0.3266)
	grad:  2.0 4.0 tensor(-1.2802)
	grad:  3.0 6.0 tensor(-2.6500)
Progress: 6 tensor(0.1951)
	grad:  1.0 2.0 tensor(-0.2414)
	grad:  2.0 4.0 tensor(-0.9465)
	grad:  3.0 6.0 tensor(-1.9592)
Progre